web/router.ex
defmodule Cms.Router do
  use Cms.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Cms do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/registrations", RegistrationController, only: [:new, :create]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", Cms do
  #   pipe_through :api
  # end
end

lib/cms/endpoint.ex
defmodule Cms.Endpoint do
  use Phoenix.Endpoint, otp_app: :cms

  socket "/socket", Cms.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :cms, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_cms_key",
    signing_salt: "fEP9PuyQ"

  plug Cms.Router
end

lib/cms/repo.ex
defmodule Cms.Repo do
  use Ecto.Repo, otp_app: :cms
end

web/models/registration.ex
defmodule Cms.Registration do
	import Ecto.Changeset, only: [put_change: 3]

	def create(changeset ,repo) do
		changeset
		|> put_change(:crypted_password, hashed_password(changeset.params["password"]))
		|> repo.insert()
	end

	defp hashed_password(password) do
		Comeonin.Bcrypt.hashpwsalt(password)
	end
end

web/models/session.ex
defmodule Cms.Session do
	alias Cms.User

	def login(params, repo) do
		user = repo.get_by(User, email: String.downcase(params["email"]))
		case authenticate(user, params["password"]) do
			true -> {:ok, user}
			_ 	 -> :error
		end
	end

	def current_user(conn) do
		id = Plug.Conn.get_session(conn, :current_user)
		if id, do: Cms.Repo.get(User, id)
	end

	def logged_in?(conn), do: !!current_user(conn)

	defp authenticate(user, password) do
		case user do
		   nil -> false
		   _   -> Comeonin.Bcrypt.checkpw(password, user.crypted_password)
		    
		end
	end
end

web/models/user.ex
defmodule Cms.User do
  use Cms.Web, :model

  schema "users" do
    field :email, :string
    field :crypted_password, :string
    field :password, :string, virtual: true

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :password])
    |> validate_required([:email, :password])
    |> unique_constraint(:email)
    |> validate_format(:email, ~r/@/)
    |> validate_length(:password, min: 5)
  end
end

web/controllers/page_controller.ex
defmodule Cms.PageController do
  use Cms.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/registration_controller.ex
defmodule Cms.RegistrationController do
	use Cms.Web, :controller
	alias Cms.User

	def new(conn, __params) do
		changeset = User.changeset(%User{})
		render conn, changeset: changeset
	end

	def create(conn, %{"user" => user_params}) do
		changeset = User.changeset(%User{}, user_params)

		case Cms.Registration.create(changeset, Cms.Repo) do
		   {:ok, changeset}->
				conn
				|> put_session(:current_user, changeset.id)
				|> put_flash(:info, "Your account was created")
				|> redirect(to: "/")
		   {:error, changeset} ->
		    	conn
		    	|> put_flash(:info, "Unable to create account")
		    	|> render("new.html", changeset: changeset)
		end
	end
end

web/controllers/session_controller.ex
defmodule Cms.SessionController do
	use Cms.Web, :controller

	def new(conn, __params) do
		render conn, "new.html"
	end

	def create(conn, %{"session" => session_params}) do
		case Cms.Session.login(session_params, Cms.Repo) do
			{:ok, user} ->
				conn
				|> put_session(:current_user, user.id)
				|> put_flash(:info, "Logged in")
				|> redirect(to: "/")
			:error ->
				conn
				|> put_flash(:info, "Wrong email or password")
				|> render("new.html")	
		end
	end

	def delete(conn, __params) do
		conn
		|> delete_session(:current_user)
		|> put_flash(:info, "Logged out!")
		|> redirect(to: "/")
	end
end

web/views/error_view.ex
defmodule Cms.ErrorView do
  use Cms.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Cms.LayoutView do
  use Cms.Web, :view
end

web/views/page_view.ex
defmodule Cms.PageView do
  use Cms.Web, :view
end

web/views/registration_view.ex
defmodule Cms.RegistrationView do
	use Cms.Web, :view
end

web/views/session_view.ex
defmodule Cms.SessionView do
	use Cms.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Cms!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if logged_in?(@conn) do %>
              <li><%= current_user(@conn).email%></li>
              <li><%= link "Logout", to: session_path(@conn, :delete), method: :delete%></li>
            <%= else %>  
                <li><%= link "Login", to: "/login"%></li>
                <li><%= link "Register", to: registration_path(@conn, :new)%></li>
            <%= end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
</div>

web/templates/session/new.html.eex
<h2>Login</h2>

<%= form_for @conn, session_path(@conn, :create), [name: :session], fn f -> %>
  <div class="form-group">
    <label>Email</label>
    <%= text_input f, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Password</label>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Login", class: "btn btn-primary" %>
  </div>
<% end %>